### ISSUE TITLE
https:// support

### ISSUE THREAD

**Issue by Motophan** [ckcr4lyf/qbit-race#10]
If qbittorrent is in a docker container behind nginx, traefik, or caddy, oftentimes the simplest way to connect to it would be to run through your reverseproxy.

Most reverseproxies by default redirect http to https, but this software will not follow the redirect.

If I specify https:// in the .env file, it will go to http://https://sub.domian.tld

**Comment by Motophan** [comment]
This could alternatively be fixed w/ a section in the readme about docker. https support would be preferable, but if this is not something doable then editing the readme to something to the effect of:

Docker Specific Settings:

If you run qbittorrent in a docker container on the default bridge, you need to specify the container's IP address. To find this, run `docker network ls`, then `docker network inspect networkname` to find the container IP address on the bridge. It will be in 172.X.0.Y

From there it will accept http connections as it buypasses your reverseproxy.

**Comment by ckcr4lyf** [comment]
This has been fixed thanks to #17
