### ISSUE TITLE
[Discord Webhook] Incorrect Notification for non-existing file

### ISSUE THREAD

**Issue by evman** [ckcr4lyf/qbit-race#22]
For some reason, qbit-race's discord webhook keeps sending a non-existing notification to the channel it's assigned to.  The notification mentions that the torrent: "Ubuntu 20.04 LTS" has been added.  The first time this happened was when the webhook was initially added to my channel, and it just happened again.  This file does not exist and is nowhere to be found in my AutoDL-IRSSI logs.  Here is a screenshot of what the notification looks like.

![Qbit-Race_Webhook_Issue](https://user-images.githubusercontent.com/4967875/142575875-304eeb7a-55db-4e5f-9de9-5058ea0b9301.png)

**Comment by ckcr4lyf** [comment]
Usually, if you run `npm run validate`, it will run a script which sends this dummy notification, to make sure you've set it up correctly. 

Can you confirm, if this happens in that case, or when a torrent is completed, or just randomly?

**Comment by evman** [comment]
> npm run validate

@ckcr4lyf That would be the reason it was happening!  Thank you so much for the quick reply, this script is truly amazing, I absolutely love it.  Thank you for all of the time you spent making this!

**Comment by ckcr4lyf** [comment]
Cheers, glad it got sorted! I'll add this to the documentation as well, so it is less surprising to folks in the future
