### ISSUE TITLE
Incorrect HTTP Method for login (qBittorrent 4.4+)

### ISSUE THREAD

**Issue by stevezau** [ckcr4lyf/qbit-race#32]
Hi,

Is this meant to work with qbittorrent 4.5.2?

I get an error on launch. It tries to log into qbittorrent but gets a "Method Not Allowed" to the URL 

https://xxxxxx/api/v2/auth/login?username=xxxx&password=xxxx

Thanks

**Comment by ckcr4lyf** [comment]
I've not actually tested it, let me check it now.

**Comment by ckcr4lyf** [comment]
@stevezau could you confirm if you're using the latest stable release v1.1.0 (https://github.com/ckcr4lyf/qbit-race/releases/tag/v1.1.0) , or the latest master?

**Comment by stevezau** [comment]
I installée via npm so I assume that's using whatever is the latest package on npm?

I did see a note in the read me read the versions but I noticed no commits since 2022 so I assumed the latest dev branch would work

**Comment by ckcr4lyf** [comment]
Gotcha, let me test that version and get back to you.

**Comment by stevezau** [comment]
Thanks!

I was also considering writing a dockerfile for this.. if you're interested?

**Comment by ckcr4lyf** [comment]
I can confirm, latest master does _NOT_ work with v4.4+. Let me fix it.

RE: Docker, it there is a valid use case then sure. I've never used qbit in docker so not sure what it would look like, in terms of the config for qbit-race etc. Perhaps we can discuss it further in #14 , or you could open a new issue

**Comment by ckcr4lyf** [comment]
@stevezau should be fixed, Please run `npm update -g qbit-race` to update and then try again!

**Comment by stevezau** [comment]
```023-05-26T07:34:22.071Z [DBG]: Config file exists. Will try reading it
2023-05-26T07:34:22.075Z [INF]: Starting...
2023-05-26T07:34:22.082Z [DBG]: Going to add torrent from /data/downloads/xxxx, and set category undefined
file:///usr/local/lib/node_modules/qbit-race/build/src/qbittorrent/auth.js:8
        throw new Error(`Failed to authenticate`);
              ^

Error: Failed to authenticate
    at loginV2 (file:///usr/local/lib/node_modules/qbit-race/build/src/qbittorrent/auth.js:8:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Command.<anonymous> (file:///usr/local/lib/node_modules/qbit-race/bin/index.mjs:63:17)

Node.js v18.13.0```

**Comment by ckcr4lyf** [comment]
> That didn't work.

Does `qbit-race validate` work?

**Comment by stevezau** [comment]
@ckcr4lyf no, it comes back with the below.

Can i see debug output somehow? 

```
2023-05-26T21:54:53.781Z [DBG]: Config file exists. Will try reading it
2023-05-26T21:54:53.785Z [INF]: Starting...
2023-05-26T21:54:53.789Z [INF]: Going to login
2023-05-26T21:54:54.117Z [ERR]: Validation failed! Error: Failed to authenticate```

**Comment by ckcr4lyf** [comment]
Let me improve the logs and let you know so you can update it.

**Comment by ckcr4lyf** [comment]
@stevezau I've updated it to differentiate between incorrect credentials and other UNKNOWN ERRORS with more logging. Can you update (`npm update -g qbit-race`) and then try again?

**Comment by stevezau** [comment]
Ahh, i figured it out. I had to disable Enable Host header validation
