### ISSUE TITLE
[FEATURE REQUEST] CLI Option to set tags when adding torrents

### ISSUE THREAD

**Issue by Kuredant** [ckcr4lyf/qbit-race#40]
### Problem

When adding a torrent `qbit-race add`, only the tracker hostname is set as a tag.
It would be great if:
- this behavior could be optionally disabled (I already use qbit_manage to tag by tracker)
- we had the ability to specify different tags when adding a torrent

This would help with torrent organization, especially when `qbit-race add` is called from different places.

### Proposal

- Add a command line flag to `qbit-race add` to disable default tracker hostname tagging
- Add a command line flag to `qbit-race add` which accepts one or multiple tags, and sets it while adding the torrent to qBittorrent.

E.g. `qbit-race add -p file.torrent --category "Debian Based Distros" --no-tracker-tag --tag "autodl" --tag "racing"`

**Comment by ckcr4lyf** [comment]
Thanks for the suggestion. I will definitely add an option to disable auto-tag.

For custom extra tags, I might go with `--tags "first,second"` i.e. a CSV, just because it might be simpler with the library. TBD.

**Comment by ckcr4lyf** [comment]
@Kuredant you can now update qbit-race (`npm update -g qbit-race`) , and try out the option `--no-tracker-tags` (note: extra 's' compared to previous discussion).

Docs: https://github.com/ckcr4lyf/qbit-race#no-tracker-tags

Sorry I'm traveling so haven't gotten around to the custom tags thingy, will be next.

**Comment by Kuredant** [comment]
> @Kuredant you can now update qbit-race (npm update -g qbit-race) , and try out the option --no-tracker-tags (note: extra 's' compared to previous discussion).

Awesome, thank you!

**Comment by ckcr4lyf** [comment]
@Kuredant also added the option for extra tags: https://github.com/ckcr4lyf/qbit-race#extra-tags

You'll need to update `qbit-race` and then you should be good to go. 

If there are any issues feel free to reopen this one.
