### ISSUE TITLE
Resume torrents failing after completed race

### ISSUE THREAD

**Issue by durgins** [ckcr4lyf/qbit-race#43]
When running qbit-race with the completed option, it isn't resuming torrents in qBittorrent 4.6.0 with an error in the log file:

2023-11-20T22:22:28.161Z [ERR]: Failed to resume torrents! Error: Failed to resume torrents. Error: AxiosError: Request failed with status code 405

I looked this up and it looks like 405 is usually returned when using a GET method when POST is wanted.

The problem seems to lie here : https://github.com/ckcr4lyf/qbit-race/blob/1882490431741d7c603f6df0c3381932c9906c4c/src/qbittorrent/api.ts#L102-L104

I see that other things like pausing the torrents, adding tags, etc are all using POST and they are working.  Is there any reason why this was coded with GET?   If so, would a fallback to POST on failure fix my problem?

**Comment by ckcr4lyf** [comment]
Related to #39 I think. Initially the API worked with both GET and POST, though as per spec it should be POST

Over time they started to enforce this. Let me fix it for this endpoint, and update the release.

**Comment by durgins** [comment]
Awesome, thanks for the quick response!  I did just test it by copying and pasting the pause torrent snippet, changing it to resume and it worked.  So it's good for me at the moment if you want to take your time to update the release.

**Comment by ckcr4lyf** [comment]
@durgins I've released the fixed version. 

You can update it by running:

```
npm update -g qbit-race
```

I am not entirely sure how this affects manual patches, but I guess it will just overwrite it.
