### ISSUE TITLE
No such method TorrentsController::pauseAction()

### ISSUE THREAD

**Issue by Aubermean** [ckcr4lyf/qbit-race#52]
`Failed to pause torrents: AxiosError: Request failed with status code 404`

`QMetaObject::invokeMethod: No such method TorrentsController::pauseAction()`

Is my Qbittorrent version the issue? Is V5 not supported?

**Comment by ckcr4lyf** [comment]
It is very likely related to v5 yes, I've not tested it on v5. Have you previously used this tool on v4 before?

Could you also share more detailed logs, or at what point / step this occurred?

**Comment by relik7** [comment]
I worked with you previously on issue #43.  This seems to be another API change in qBittorrent v5 where they removed references to pausing torrents and now always refer to it as stopping.

I changed this line to fix it in build/src/qbittorrent/api.js: `ApiEndpoints["pauseTorrents"] = "/api/v2/torrents/pause";`
was changed to:
 `ApiEndpoints["pauseTorrents"] = "/api/v2/torrents/stop";`

I don't know how you want to fix it, whether it be through a config variable for version 5 or whether you try the stop endpoint and if it fails try the pause endpoint (fallback to version 4). I would also suggest that the failure to pause torrents shouldn't be a fatal error like it is now. It should print the error and continue.

With that small change above, qbit-race is continuing to work well for me with qBittorrent v5.0.3.  Thank you again for developing it.

**Comment by ckcr4lyf** [comment]
Hey @relik7 , thanks for confirming its due to the v5 change. I'll make a change today to make it compatible with the new version after some testing. 

Cheers.

**Comment by ckcr4lyf** [comment]
Caused due to:

* https://github.com/qbittorrent/qBittorrent/issues/19041
* https://github.com/qbittorrent/qBittorrent/pull/20532/

**Comment by ckcr4lyf** [comment]
Should be fixed now, just update to the latest version!
