### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by khius** [ckcr4lyf/qbit-race#8]
If I go forward past this warning
<img width="459" alt="Screen Shot 2020-12-24 at 10 33 07 PM" src="https://user-images.githubusercontent.com/6244107/103117626-3fa83300-4639-11eb-9acc-086e29b3a855.png">
It gives me this error when trying to validate
<img width="915" alt="Screen Shot 2020-12-24 at 10 45 14 PM" src="https://user-images.githubusercontent.com/6244107/103117733-d1b03b80-4639-11eb-8619-b3be27c14c78.png">
btw I edited the .env file with the right username and password.

**Comment by ckcr4lyf** [comment]
Did you copy the `sample.env` file to `.env` and configure the username and password?

**Comment by ckcr4lyf** [comment]
To me, it most likely is wrong username and /or password. One other thing I can suggest is manually logging in with this curl command:

```sh
curl --request GET --url 'http://127.0.0.1:[QBIT_WEBUI_PORT]/api/v2/auth/login?username=[USERNAME]&password=[PASSWORD]' -v
```

This is the response I get:
```
*   Trying 127.0.0.1:8080...
* Connected to 127.0.0.1 (127.0.0.1) port 8080 (#0)
> GET /api/v2/auth/login?username=REDACTED&password=REDACTED HTTP/1.1
> Host: 127.0.0.1:8080
> User-Agent: curl/7.69.1
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< connection: keep-alive
< content-length: 3
< content-security-policy: default-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; script-src 'self' 'unsafe-inline'; object-src 'none'; form-action 'self'; frame-ancestors 'self';
< content-type: text/plain
< date: Fri, 25 Dec 2020 05:42:35 GMT
< referrer-policy: same-origin
< set-cookie: SID=REDACTED; HttpOnly; path=/; SameSite=Strict
< x-content-type-options: nosniff
< x-frame-options: SAMEORIGIN
< x-xss-protection: 1; mode=block
<
* Connection #0 to host 127.0.0.1 left intact
Ok.
```

**Comment by khius** [comment]
Thank you for your answer
I initially changed the qbit_host from 127.0.0.1 to the ipaddress/qbittorent and that was the problem
